### PR TITLE
Release with hotfixes

### PR DESCRIPTION
**Pull request by NotJustAnna**
**Reason for the change**
Release a hotfix to partial sequences and adds shutdown reasons to the response pump, which should help debug a later issue.

**Description**
Result.java code related to partial sequences was moved out to a inner class.

**Code examples**
No code changes.

**Checklist**
- [x] I have read and agreed to the [RethinkDB Contributor License Agreement](http://rethinkdb.com/community/cla/)

**References**
None.

### CODE REVIEW

**Comment by NotJustAnna** [comment]
I don't understand why the tests fails, to be honest. Running locally works just fine.

**Comment by martinpaljak** [comment]
FYI: there is still a hang with partials (the test that directly calls .toList() hang intermittently).

I'll deploy it to see what the exception with pumps is.

**Comment by NotJustAnna** [comment]
.toList() hanging? Lemme see. Did I break aggressive fetch mode?

**Comment by martinpaljak** [comment]
https://repo1.maven.org/maven2/com/rethinkdb/rethinkdb-driver/2.4.4/ <- that looks messy.

**Comment by NotJustAnna** [comment]
Lol what? That's really confusing.

**Comment by NotJustAnna** [comment]
Uhh.. I'll try solve this with Boros once we can. (cc @gabor-boros)

Something on our publish routine is publishing the old version binaries with the new ones.
- v2.4.3 folder contains v2.4.3 and v2.4.2
- v2.4.4 folder contains v2.4.4, v2.4.3 and v2.4.2

**Comment by gabor-boros** [comment]
Hell. I guess it’s that I forgot to remove the previous versions before deploy. I’ll redeploy the affected versions tomorrow

**Comment by gabor-boros** [comment]
If that’s possible

**Comment by martinpaljak** [comment]
"mvn clean deploy" or whatever is the equivalent with gradle should be the standard procedure.

**Pull request merged**
